dist: trusty
sudo: required
language: node_js

node_js:
  - "10"

matrix:
  fast_finish: true
  allow_failures:
    - env: 'TASK=coverage'
  
jobs:
  include:
    - stage: compile
      install: npm install -g truffle
      before_script: npm install openzeppelin-solidity@1.12.0
      script: truffle compile
    - stage: test and coverage
      env: 'TASK=coverage'
      install: npm install -g truffle coveralls
      before_script: npm install solidity-coverage ethereumjs-abi openzeppelin-solidity@1.12.0
      script: npm run coverage && cat coverage/lcov.info | coveralls